def pytest_html_report_title(report):
    report.title = "QA-Learning Test Report"

def pytest_html_results_summary(prefix, summary, postfix):
    prefix.extend([
        "This report was generated by pytest + pytest-html. ",
        "Marker 'browser' identifies Playwright tests."
    ])
